/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/mariaochoadiez/Downloads/laptop.glb 
Author: Aullwen (https://sketchfab.com/Aullwen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-7d870e900889481395b4a575b9fa8c3e
Title: Laptop
*/

import { useGLTF } from "@react-three/drei";
import { useEffect, useRef } from "react";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { useScreenTexture } from "./useScreenTexture";

const Laptop = (props: any) => {
  const { nodes } = useGLTF("./laptop.glb") as any;
  const screenRef = useRef<THREE.Mesh>(null);
  const screenTexture = useScreenTexture();

  useEffect(() => {
    const geo = nodes.Screen_ComputerScreen_0.geometry;

    geo.computeBoundingBox();
    const box = geo.boundingBox;
    if (!box) return;

    const pos = geo.attributes.position;
    const uv = [];

    for (let i = 0; i < pos.count; i++) {
      const x = pos.getX(i);
      const y = pos.getY(i);

      const u = (x - box.min.x) / (box.max.x - box.min.x);
      const v = (y - box.min.y) / (box.max.y - box.min.y);

      uv.push(u, v);
    }

    geo.setAttribute("uv", new THREE.Float32BufferAttribute(uv, 2));
  }, []);

  useFrame(() => {
    if (!screenRef.current) return;

    const mat = screenRef.current.material as THREE.MeshStandardMaterial;
    mat.emissiveIntensity = THREE.MathUtils.lerp(
      mat.emissiveIntensity,
      props.zooming ? 1.4 : 0.6,
      0.08,
    );
  });

  return (
    <group {...props}>
      <mesh
        geometry={nodes.Frame_ComputerFrame_0.geometry}
        material={nodes.Frame_ComputerFrame_0.material}
        position={[0, 0.976, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
        onClick={props.onClick}
      />

      <mesh
        ref={screenRef}
        geometry={nodes.Screen_ComputerScreen_0.geometry}
        position={[0, 0.65, -10.3]}
        scale={[100, 100, 88.235]}
      >
        <meshStandardMaterial
          map={screenTexture}
          emissiveMap={screenTexture}
          emissive="#ffffff"
          emissiveIntensity={1}
          roughness={1}
          metalness={0}
          toneMapped={false}
        />
      </mesh>
    </group>
  );
};

export default Laptop;
